#!/bin/sh

COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme)

case $COLOR_SCHEME in
	"'prefer-dark'")
		exec /etc/gammastep/hooks/change-color-scheme period-changed none daytime
		;;
	*)
		exec /etc/gammastep/hooks/change-color-scheme period-changed none night
		;;
esac
